definitions:
  github_com_mohsen104_web-api_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_mohsen104_web-api_api_validations.ValidationError'
        type: array
    type: object
  github_com_mohsen104_web-api_api_validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  services.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
info:
  contact: {}
paths:
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp
      parameters:
      - description: GetOtpRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_mohsen104_web-api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_mohsen104_web-api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_mohsen104_web-api_api_helper.BaseHttpResponse'
      summary: Send otp
      tags:
      - users
swagger: "2.0"
