services:
  setup:
    build:
      context: elk/setup/
      args:
        ELASTIC_VERSION: 8.5.3
    init: true
    volumes:
      - ./elk/setup/entrypoint.sh:/entrypoint.sh:ro
      - ./elk/setup/helpers.sh:/helpers.sh:ro
      - ./elk/setup/roles:/roles:ro
      - setup:/state
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-changeme}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-changeme}
    networks:
      - webapi_network
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elk/elasticsearch/
      args:
        ELASTIC_VERSION: 8.5.3
    container_name: elasticsearch
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      discovery.type: single-node
    networks:
      - webapi_network
    restart: unless-stopped

  kibana:
    build:
      context: elk/kibana/
      args:
        ELASTIC_VERSION: 8.5.3
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-changeme}
    networks:
      - webapi_network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    build:
      context: elk/filebeat/
      args:
        ELASTIC_VERSION: 8.5.3
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
      - ./elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../src/logs:/var/log/filebeat/service:ro
      - logs:/var/log/filebeat
    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-changeme}
      BEATS_SYSTEM_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-changeme}
    networks:
      - webapi_network
    depends_on:
      - elasticsearch

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_sale_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapi_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: h.naimaei@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - webapi_network
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis_container
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - webapi_network

volumes:
  postgres:
  pgadmin:
  redis:
  logs:
  setup:
  elasticsearch:

networks:
  webapi_network:
    driver: bridge
